# This is the Docker stack for development.
# You can remote into the 'app' container to do some development work,
# and all changes will be available in the project folder.
# for production uses, please use docker-compose.prod.yml

volumes:
  database:

services:
  app:
    build:
      dockerfile: ./Dockerfile.dev
    container_name: ${COMPOSE_PROJECT_NAME}-dev-app
    hostname: ${COMPOSE_PROJECT_NAME}-dev-app
    depends_on: [ database ]
    tty: true
    privileged: true
    user: ${DOCKER_UID}:${DOCKER_GID}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - 8870:80
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      - ./:${HOME}/${COMPOSE_PROJECT_NAME}
    restart: unless-stopped

  database:
    image: mariadb:lts-noble
    container_name: ${COMPOSE_PROJECT_NAME}-dev-database
    hostname: ${COMPOSE_PROJECT_NAME}-dev-database
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${DB_DATABASE}
    ports:
      - 8871:3306
    volumes:
      - database:/var/lib/mysql

  adminer:
    image: adminer
    container_name: ${COMPOSE_PROJECT_NAME}-dev-adminer
    depends_on: [ database ]
    ports:
      - 8872:8080
    restart: unless-stopped


